// Joke generator module

function getRandomJoke() {
    const jokes = [
        "Why don't programmers like nature? It has too many bugs. — Anonymous",
        "Why do Java developers wear glasses? Because they don't see sharp. — Anonymous",
        "How many programmers does it take to change a light bulb? None, that's a hardware problem. — Anonymous",
        "Why did the computer show up at work late? It had a hard drive. — Anonymous",
        "Why do programmers prefer dark mode? Because light attracts bugs. — Anonymous",
        "What do you call 8 hobbits? A hobbyte. — Anonymous",
        "Why was the JavaScript developer sad? Because he didn't 'null' his feelings. — Anonymous",
        "Why did the developer go broke? Because he used up all his cache. — Anonymous",
        "Why do Python programmers have low self-esteem? Because they're constantly comparing their self to others. — Anonymous",
        "Why did the function return early? Because it had a date with an exception. — Anonymous",
        // Additional programming jokes with credits
        "There are only 10 types of people in the world: those who understand binary and those who don't. — Anonymous",
        "A SQL query walks into a bar, walks up to two tables and asks: 'Can I join you?' — Reddit",
        "Why do programmers hate spaces? Because they can't tab into them. — Anonymous",
        "Why did the programmer quit his job? Because he didn't get arrays. — Anonymous",
        "Why do JavaScript developers wear glasses? Because they don't C#. — Anonymous",
        "Why was the developer unhappy at their job? They wanted arrays. — @thepracticaldev",
        "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25. — Anonymous",
        "Knock knock. Who’s there? Recursion. Recursion who? Knock knock. — @iamdevloper",
        "A programmer's wife tells him: 'While you're at the store, buy some eggs.' He never comes back. — Anonymous",
        "To understand what recursion is, you must first understand recursion. — Anonymous",
        "Why do programmers prefer iOS development? Because on Android, the Java is never strong enough. — Anonymous",
        "Why did the developer go broke? Because he used up all his cache. — Anonymous",
        "Why do programmers prefer using the dark mode? Because light attracts bugs. — Anonymous",
        "Why did the computer get cold? Because it left its Windows open. — Anonymous",
        "Why did the developer go broke? Because he lost his domain in a bet. — Anonymous",
        "Why did the coder get kicked out of school? Because he kept taking classes. — Anonymous",
        "Why do programmers prefer Linux? Because they can't C: drive. — Anonymous",
        "Why did the developer go broke? Because he couldn't commit to saving. — Anonymous",
        "Why do programmers hate nature? It has too many bugs. — Anonymous",
        "Why did the developer go broke? Because he didn't have enough cache. — Anonymous",
        "Why do programmers prefer dark mode? Because the light attracts bugs. — Anonymous",
        "Why did the developer go broke? Because he lost his cache. — Anonymous",
        // 25 more general jokes
        "Why don't scientists trust atoms? Because they make up everything. — Anonymous",
        "Why did the scarecrow win an award? Because he was outstanding in his field. — Anonymous",
        "Why don't skeletons fight each other? They don't have the guts. — Anonymous",
        "What do you call fake spaghetti? An impasta. — Anonymous",
        "Why did the bicycle fall over? Because it was two-tired. — Anonymous",
        "Why can't you hear a pterodactyl go to the bathroom? Because the 'P' is silent. — Anonymous",
        "What do you call cheese that isn't yours? Nacho cheese. — Anonymous",
        "Why did the math book look sad? Because it had too many problems. — Anonymous",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one. — Anonymous",
        "Why did the tomato turn red? Because it saw the salad dressing. — Anonymous",
        "Why did the chicken join a band? Because it had the drumsticks. — Anonymous",
        "Why can't your nose be 12 inches long? Because then it would be a foot. — Anonymous",
        "Why did the coffee file a police report? It got mugged. — Anonymous",
        "Why did the stadium get hot after the game? All the fans left. — Anonymous",
        "Why did the cookie go to the hospital? Because it felt crummy. — Anonymous",
        "Why did the man run around his bed? Because he was trying to catch up on his sleep. — Anonymous",
        "Why did the picture go to jail? Because it was framed. — Anonymous",
        "Why did the banana go to the doctor? Because it wasn't peeling well. — Anonymous",
        "Why did the music teacher need a ladder? To reach the high notes. — Anonymous",
        "Why did the computer go to the doctor? Because it had a virus. — Anonymous",
        "Why did the cow win an award? Because she was outstanding in her field. — Anonymous",
        "Why did the fish blush? Because it saw the ocean's bottom. — Anonymous",
        "Why did the grape stop rolling? Because it ran out of juice. — Anonymous",
        "Why did the bee get married? Because he found his honey. — Anonymous",
        "Why did the pencil go to the principal's office? Because it was acting sharp. — Anonymous",
        // 20 jokes from famous people
        "I used to sell furniture for a living. The trouble was, it was my own. — Les Dawson",
        "I told my wife the truth. I told her I was seeing a psychiatrist. Then she told me the truth: that she was seeing a psychiatrist, two plumbers, and a bartender. — Rodney Dangerfield",
        "I haven't spoken to my wife in years. I didn't want to interrupt her. — Rodney Dangerfield",
        "Behind every great man is a woman rolling her eyes. — Jim Carrey",
        "I find television very educating. Every time somebody turns on the set, I go into the other room and read a book. — Groucho Marx",
        "Get your facts first, then you can distort them as you please. — Mark Twain",
        "I can resist everything except temptation. — Oscar Wilde",
        "If you want your children to listen, try talking softly to someone else. — Ann Landers",
        "I am so clever that sometimes I don't understand a single word of what I am saying. — Oscar Wilde",
        "If at first you don't succeed, then skydiving definitely isn't for you. — Steven Wright",
        "I intend to live forever. So far, so good. — Steven Wright",
        "I used to think I was indecisive, but now I'm not so sure. — Tommy Cooper",
        "A day without sunshine is like, you know, night. — Steve Martin",
        "I refuse to join any club that would have me as a member. — Groucho Marx",
        "If you think nobody cares if you're alive, try missing a couple of car payments. — Earl Wilson",
        "My fake plants died because I did not pretend to water them. — Mitch Hedberg",
        "I asked God for a bike, but I know God doesn’t work that way. So I stole a bike and asked for forgiveness. — Emo Philips",
        "I have not failed. I've just found 10,000 ways that won't work. — Thomas Edison",
        "If you think you are too small to make a difference, try sleeping with a mosquito. — Dalai Lama",
        "I am not afraid of death; I just don't want to be there when it happens. — Woody Allen"
    ];
    return jokes[Math.floor(Math.random() * jokes.length)];
}
