// Quote generator module

function getRandomQuote() {
    const quotes = [
        "Code is like humor. When you have to explain it, it’s bad. — Cory House",
        "Programs must be written for people to read, and only incidentally for machines to execute. — Harold Abelson",
        "First, solve the problem. Then, write the code. — John Johnson",
        "Experience is the name everyone gives to their mistakes. — Oscar Wilde",
        "In order to be irreplaceable, one must always be different. — Coco Chanel",
        "Java is to JavaScript what car is to Carpet. — Chris Heilmann",
        "Knowledge is power. — Francis Bacon",
        "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code. — Dan Salomon",
        "Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away. — Antoine de Saint-Exupery",
        "Ruby is rubbish! PHP is phpantastic! — Nikita Popov",
        "Code never lies, comments sometimes do. — Ron Jeffries",
        "Fix the cause, not the symptom. — Steve Maguire",
        "Optimism is an occupational hazard of programming: feedback is the treatment. — Kent Beck",
        "Simplicity is the soul of efficiency. — Austin Freeman",
        "Before software can be reusable it first has to be usable. — Ralph Johnson",
        "Make it work, make it right, make it fast. — Kent Beck",
        "The best error message is the one that never shows up. — Thomas Fuchs",
        "The most disastrous thing that you can ever learn is your first programming language. — Alan Kay",
        "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. — Martin Fowler",
        "Programming isn't about what you know; it's about what you can figure out. — Chris Pine",
        // Additional 50 quotes
        "Talk is cheap. Show me the code. — Linus Torvalds",
        "Walking on water and developing software from a specification are easy if both are frozen. — Edward V. Berard",
        "If debugging is the process of removing software bugs, then programming must be the process of putting them in. — Edsger Dijkstra",
        "The most important property of a program is whether it accomplishes the intention of its user. — C.A.R. Hoare",
        "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. — Bill Gates",
        "The only way to learn a new programming language is by writing programs in it. — Dennis Ritchie",
        "Controlling complexity is the essence of computer programming. — Brian Kernighan",
        "The function of good software is to make the complex appear to be simple. — Grady Booch",
        "Simplicity is prerequisite for reliability. — Edsger Dijkstra",
        "Programming is the art of telling another human being what one wants the computer to do. — Donald Knuth",
        "A good programmer is someone who always looks both ways before crossing a one-way street. — Doug Linder",
        "The trouble with programmers is that you can never tell what a programmer is doing until it’s too late. — Seymour Cray",
        "It’s not a bug – it’s an undocumented feature. — Anonymous",
        "Software and cathedrals are much the same – first we build them, then we pray. — Sam Redwine",
        "The best thing about a boolean is even if you are wrong, you are only off by a bit. — Anonymous",
        "Weeks of programming can save you hours of planning. — Anonymous",
        "Deleted code is debugged code. — Jeff Sickel",
        "There are two ways to write error-free programs; only the third one works. — Alan J. Perlis",
        "Computers are good at following instructions, but not at reading your mind. — Donald Knuth",
        "The sooner you start to code, the longer the program will take. — Roy Carlson",
        "A language that doesn’t affect the way you think about programming is not worth knowing. — Alan J. Perlis",
        "The best programmers are not marginally better than others, they are an order of magnitude better. — Randall E. Stross",
        "Programming is not easy like Sunday morning, it is silent poetry. — Waseem Latif",
        "Programming is like writing a book... except if you miss out a single comma on page 126 the whole thing makes no sense. — Anonymous",
        "The computer was born to solve problems that did not exist before. — Bill Gates",
        "If you think your users are idiots, only idiots will use it. — Linus Torvalds",
        "The best performance improvement is the transition from the nonworking state to the working state. — John Ousterhout",
        "A primary cause of complexity is that software vendors uncritically adopt almost any feature that users want. — Niklaus Wirth",
        "The hardest part of design is keeping features out. — Donald Norman",
        "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge. — Stephen Hawking",
        "The best way to get a project done faster is to start sooner. — Jim Highsmith",
        "If you automate a mess, you get an automated mess. — Rod Michael",
        "The purpose of software engineering is to control complexity, not to create it. — Pamela Zave",
        "If builders built buildings the way programmers wrote programs, then the first woodpecker that came along would destroy civilization. — Gerald Weinberg",
        "The cheapest, fastest, and most reliable components are those that aren’t there. — Gordon Bell",
        "The most effective debugging tool is still careful thought, coupled with judiciously placed print statements. — Brian Kernighan",
        "The best code is no code at all. — Jeff Atwood",
        "A program is never less than 90% complete, and never more than 95% complete. — Terry Baker",
        "A user interface is like a joke. If you have to explain it, it’s not that good. — Martin LeBlanc",
        "If you don’t handle exceptions, your program will. — Anonymous",
        "The best method for accelerating a computer is the one that boosts it by 9.8 m/s². — Anonymous",
        "Programming is the closest thing we have to magic. — Anonymous",
        "If you don’t fail at least 90 percent of the time, you’re not aiming high enough. — Alan Kay",
        "The best way to predict the future is to invent it. — Alan Kay",
        "A computer once beat me at chess, but it was no match for me at kickboxing. — Emo Philips",
        "Computers are fast; programmers keep it slow. — Anonymous",
        "If you don’t care about quality, you can meet any other requirement. — Gerald Weinberg",
        "The best thing about a boolean is even if you are wrong, you are only off by a bit. — Anonymous",
        "Programming is not about typing, it’s about thinking. — Rich Hickey",
        "The most important single aspect of software development is to be clear about what you are trying to build. — Bjarne Stroustrup",
        "The computer is a moron. — Peter Drucker",
        "The best way to learn is to do. — Paul Halmos",
        "The only way to go fast, is to go well. — Robert C. Martin",
        "If you want to go fast, go alone. If you want to go far, go together. — African Proverb",
        // Famous people quotes
        "The only thing we have to fear is fear itself. — Franklin D. Roosevelt",
        "That’s one small step for man, one giant leap for mankind. — Neil Armstrong",
        "I have a dream. — Martin Luther King Jr.",
        "Float like a butterfly, sting like a bee. — Muhammad Ali",
        "Imagination is more important than knowledge. — Albert Einstein",
        "The greatest glory in living lies not in never falling, but in rising every time we fall. — Nelson Mandela",
        "The journey of a thousand miles begins with one step. — Lao Tzu",
        "You miss 100% of the shots you don’t take. — Wayne Gretzky",
        "Be yourself; everyone else is already taken. — Oscar Wilde",
        "In the end, we will remember not the words of our enemies, but the silence of our friends. — Martin Luther King Jr.",
        "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. — Ralph Waldo Emerson",
        "The only true wisdom is in knowing you know nothing. — Socrates",
        "Success is not final, failure is not fatal: It is the courage to continue that counts. — Winston Churchill",
        "The best way to find yourself is to lose yourself in the service of others. — Mahatma Gandhi",
        "Happiness is not something ready made. It comes from your own actions. — Dalai Lama",
        "The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt",
        "Do not go where the path may lead, go instead where there is no path and leave a trail. — Ralph Waldo Emerson",
        "It always seems impossible until it’s done. — Nelson Mandela",
        "The only limit to our realization of tomorrow will be our doubts of today. — Franklin D. Roosevelt",
        "You must be the change you wish to see in the world. — Mahatma Gandhi"
    ];
    return quotes[Math.floor(Math.random() * quotes.length)];
}