// Scary quote generator module

function getRandomScaryQuote() {
    const scaryQuotes = [
        "The scariest monsters are the ones that lurk within our souls. — Edgar Allan Poe",
        "Sometimes the things in the shadows are more real than the things in the light. — Anonymous",
        "We stopped checking for monsters under our bed when we realized they were inside us. — Charles Darwin",
        "There is something haunting in the light of the moon. — Joseph Conrad",
        "Monsters are real, and ghosts are real too. They live inside us, and sometimes, they win. — Stephen King",
        "I’m not afraid of the dark, I’m afraid of what’s in it. — Anonymous",
        "The night has teeth and it bites. — Anonymous",
        "It’s not the dead that haunt us, it’s the living. — Anonymous",
        "The silence is not empty, it’s full of answers. — Anonymous",
        "Sometimes the world of the living gets mixed up with the world of the dead. — The Others",
        "The last man on Earth sat alone in a room. There was a knock on the door. — Fredric Brown",
        "If you look in the mirror and say my name three times, I might just appear. — Urban Legend",
        "You feel safe in your bed, but you’re not alone. — Anonymous",
        "The woods are lovely, dark and deep. But I have promises to keep... — Robert Frost",
        "Every nightmare has a beginning. — Anonymous",
        // 50 more scary quotes
        "The footsteps you hear behind you may not be your imagination. — Anonymous",
        "The phone rang. 'Why did you leave me alone?' whispered the voice. — Anonymous",
        "Sometimes, the reflection in the mirror isn’t yours. — Anonymous",
        "The shadows move when you’re not looking. — Anonymous",
        "You lock the door and check it twice, but something is already inside. — Anonymous",
        "The eyes in the painting seem to follow you. — Anonymous",
        "The wind howled, but the whisper came from inside the house. — Anonymous",
        "You wake up, but you can’t move. Something is sitting on your chest. — Anonymous",
        "The doll’s smile is wider than you remember. — Anonymous",
        "You hear your mother calling you from the kitchen. As you walk out, you see her in your room. — Anonymous",
        "The closet door creaks open by itself every night. — Anonymous",
        "You feel a cold breath on your neck, but you’re alone. — Anonymous",
        "The lights flicker, and you see a shadow that isn’t yours. — Anonymous",
        "You hear laughter from the basement, but no one is there. — Anonymous",
        "The old music box plays by itself at midnight. — Anonymous",
        "You wake up to find scratches on your arms you didn’t have before. — Anonymous",
        "The portrait in the hallway seems to change every day. — Anonymous",
        "You hear footsteps upstairs, but you live alone. — Anonymous",
        "The TV turns on by itself, showing static and a faint face. — Anonymous",
        "You hear your name whispered in the dark. — Anonymous",
        "The attic door is open, but you never go up there. — Anonymous",
        "You see a face in the window, but you live on the tenth floor. — Anonymous",
        "The rocking chair moves, but no one is sitting in it. — Anonymous",
        "You find muddy footprints leading from the door to your bed. — Anonymous",
        "The clock always stops at 3:07 AM. — Anonymous",
        "You hear tapping on the window, but it’s not raining. — Anonymous",
        "You wake up to find your furniture rearranged. — Anonymous",
        "The mirror fogs up, and words appear: 'I see you.' — Anonymous",
        "You hear a child giggling in the hallway, but you have no children. — Anonymous",
        "The basement light is on, but you never turn it on. — Anonymous",
        "You see a shadow standing at the foot of your bed. — Anonymous",
        "The doorbell rings at midnight, but no one is there. — Anonymous",
        "You hear breathing under your bed. — Anonymous",
        "The old photograph shows someone standing behind you. — Anonymous",
        "You wake up to find your window open, though you closed it before bed. — Anonymous",
        "You hear scratching inside the walls. — Anonymous",
        "The music stops, but you still hear humming. — Anonymous",
        "You find a note on your pillow: 'Don’t look under the bed.' — Anonymous",
        "You see handprints on the bathroom mirror. — Anonymous",
        "You hear footsteps circling your bed at night. — Anonymous",
        "The lights go out, and you hear whispering. — Anonymous",
        "You feel someone watching you, but no one is there. — Anonymous",
        "You wake up to find your door wide open. — Anonymous",
        "The wind whispers your name. — Anonymous",
        "You see a shadow dart across the hallway. — Anonymous",
        "You hear a knock from inside the closet. — Anonymous",
        "You find a single black feather on your pillow. — Anonymous",
        "You hear a voice say, 'Don’t turn around.' — Anonymous",
        "You see your reflection blink when you don’t. — Anonymous",
        "You hear a lullaby coming from the basement. — Anonymous",
        "You wake up and can’t remember locking the door, but it’s locked from the inside. — Anonymous",
        "You hear a second heartbeat in your chest. — Anonymous",
        "You see writing on the wall that wasn’t there before. — Anonymous",
        "You hear a whisper: 'I’m still here.' — Anonymous",
        // Scary sayings from movies or books
        "They're here. — Poltergeist",
        "Here's Johnny! — The Shining",
        "Whatever you do, don't fall asleep. — A Nightmare on Elm Street",
        "Do you like scary movies? — Scream",
        "We all go a little mad sometimes. — Psycho",
        "Be afraid... be very afraid. — The Fly",
        "I see dead people. — The Sixth Sense",
        "It’s alive! It’s alive! — Frankenstein",
        "Redrum. — The Shining",
        "In space, no one can hear you scream. — Alien",
        "Sometimes dead is better. — Pet Sematary",
        "You’re gonna need a bigger boat. — Jaws",
        "The power of Christ compels you! — The Exorcist",
        "All work and no play makes Jack a dull boy. — The Shining",
        "They're coming to get you, Barbara. — Night of the Living Dead",
        "We have such sights to show you. — Hellraiser",
        "It rubs the lotion on its skin or else it gets the hose again. — The Silence of the Lambs",
        "A boy’s best friend is his mother. — Psycho",
        "I ate his liver with some fava beans and a nice Chianti. — The Silence of the Lambs",
        "You’ll float too. — IT",
        "Whatever walks there, walks alone. — The Haunting of Hill House",
        "The call is coming from inside the house. — When a Stranger Calls",
        "Death has come to your little town, Sheriff. — Halloween",
        "We all float down here. — IT",
        "Heeere’s Johnny! — The Shining",
        "I am your number one fan. — Misery",
        "It’s just a bunch of hocus pocus. — Hocus Pocus",
        "I’m your worst nightmare. — A Nightmare on Elm Street",
        "You’re not afraid of the dark, are you? — Are You Afraid of the Dark?",
        "There’s something wrong with this house. — The Amityville Horror"
    ];
    return scaryQuotes[Math.floor(Math.random() * scaryQuotes.length)];
}